# Generated by Django 2.0 on 2018-07-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig_name', models.CharField(max_length=30)),
                ('coordinator', models.CharField(max_length=50)),
                ('members', models.CharField(max_length=500)),
            ],
        ),
    ]
